<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Compositor.Windows</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Compositor.Imaging/Compositor.Imaging.csproj" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="4.152.1" />
  </ItemGroup>
</Project>
