using System.Text.Json.Nodes;
using Compositor.Core;
using Compositor.Imaging;
using SkiaSharp;
using Xunit;

namespace Compositor.Tests;

public sealed class ExposureTests : IDisposable
{

    [Theory]
    [InlineData("exposureSettings")][InlineData("levels")]
    public void DuplicateNestedFieldsAreRejected(string section)
    {
        var doc = Sample(); string path = Path.Combine(root, "Duplicate.comp"); ProjectStore.Save(doc, null, path);
        string file = Path.Combine(path, "manifest.json"), json = File.ReadAllText(file);
        int start = json.IndexOf('{' , json.IndexOf('"' + section + '"'));
        json = json.Insert(start + 1, "\"gamma\":1,\"gamma\":1,");
        File.WriteAllText(file, json); Assert.Throws<InvalidDataException>(() => ProjectStore.Load(path));
    }

    [Fact]
    public void NonuniformTransformedMaskKeepsItsGridAndCoverageAfterReopen()
    {
        var doc = Document.Create(520, 4);
        var source = doc.Layers[0] with { Pixels = LayerMask.Solid(520, 4, 90).Pixels };
        var adjustment = Layer.ExposureLayer(520, 4) with { Exposure = new(1), Mask = LayerMask.Solid(520, 4),
            Transform = new(5, 1, 500, 3, 17, true) };
        var stroke = new MaskStroke(adjustment, new(120, .5, 1, 0, 0, 0), 520, 4); stroke.Append(new(256, 2));
        adjustment = adjustment with { Mask = stroke.Mask }; doc = doc with { Layers = [source, adjustment] };
        string path = Path.Combine(root, "Grid.comp"); ProjectStore.Save(doc, adjustment.Id, path);
        var loaded = ProjectStore.Load(path).Document;
        Assert.Equal(520, loaded.Layers[1].Pixels.Width); Assert.Empty(loaded.Layers[1].Pixels.Tiles);
        Assert.Equal(adjustment.Mask.Pixels.ToRgba(), loaded.Layers[1].Mask!.Pixels.ToRgba());
        Assert.Equal(Render(doc), Render(loaded));
    }

    [Fact]
    public void SwiftShapedExposureFixtureOpensWithNeutralOptionalSettings()
    {
        string path = Path.Combine(root, "Swift.comp"); Directory.CreateDirectory(path);
        // Independently written from Swift Codable keys, not generated by the Windows writer.
        File.WriteAllText(Path.Combine(path, "manifest.json"), """
            {"format":"com.compositor.project","version":7,"colorSpace":"sRGB","documentID":"73C9F270-245F-4BCC-9533-BDB45313AEE4",
             "width":2,"height":2,"layers":[{"id":"5373B900-16CE-436E-ACCA-9FD899AF8B61","name":"Exposure","isVisible":true,
             "transform":{"origin":[0,0],"size":[2,2],"rotation":0,"flipX":false,"flipY":false,"sampling":"High quality"},
             "adjustment":{"kind":"Exposure","hue":0,"saturation":0,"lightness":0,"colorize":false,
             "levels":{"channel":"RGB","ranges":[{"black":0,"white":255,"gamma":1,"outputBlack":0,"outputWhite":255},
               {"black":0,"white":255,"gamma":1,"outputBlack":0,"outputWhite":255},{"black":0,"white":255,"gamma":1,"outputBlack":0,"outputWhite":255},
               {"black":0,"white":255,"gamma":1,"outputBlack":0,"outputWhite":255}]},
             "curves":{"channel":"RGB","channels":[[{"x":0,"y":0},{"x":255,"y":255}],[{"x":0,"y":0},{"x":255,"y":255}],
               [{"x":0,"y":0},{"x":255,"y":255}],[{"x":0,"y":0},{"x":255,"y":255}]]},
             "exposureSettings":{"exposure":1.5,"offset":-0.1,"gamma":1.25}}}]}
            """);
        var loaded = ProjectStore.Load(path); Assert.Equal(new ExposureAdjustment(1.5, -.1, 1.25), loaded.Document.Layers[0].Exposure);
        Assert.All(Render(loaded.Document), b => Assert.Equal(0, b));
    }

    [Fact]
    public void GroupReorderDeleteUngroupAndUndoKeepAdjustmentSemantics()
    {
        var doc = Sample(); var layer = doc.Layers[1]; var group = Layer.Group("Folder", 4, 1) with { Opacity = .5 };
        doc = doc with { Layers = [doc.Layers[0], group, layer with { ParentId = group.Id }] };
        var session = new EditorSession(doc); var expected = Render(doc);
        session.Apply(d => LayerHierarchy.Ungroup(d, group.Id)); Assert.Equal(expected, Render(session.Document));
        Assert.Equal(.5, session.Document.Layers[1].Opacity); session.Undo(); Assert.Same(doc, session.Document);
        session.Apply(d => LayerHierarchy.Reorder(d, group.Id, -1)); Assert.Equal(doc.Layers[0].Pixels.ToRgba(), Render(session.Document));
        session.Undo(); session.Apply(d => LayerHierarchy.Delete(d, group.Id)); Assert.Single(session.Document.Layers);
        session.Undo(); Assert.Equal(expected, Render(session.Document)); Assert.Equal(0, session.HistoryRetainedBytes);
    }

    [Fact]
    public void ExposureHasNoSourceBudgetButCannotOwnImagePixelsOrBeAGroup()
    {
        var doc = Document.Create(10_000, 10_000); var layer = Layer.ExposureLayer(10_000, 10_000) with { Mask = LayerMask.Solid(1, 1) };
        doc = doc with { Layers = [layer, layer with { Id = Guid.NewGuid() }] }; doc.Validate();
        Assert.Throws<InvalidDataException>(() => doc.Replace(layer with { Pixels = LayerMask.Solid(1, 1).Pixels }).Validate());
        Assert.Throws<InvalidDataException>(() => doc.Replace(layer with { IsGroup = true, Mask = null }).Validate());
    }

    private readonly string root = Path.Combine(Path.GetTempPath(), "CompositorExposure-" + Guid.NewGuid().ToString("N"));
    public ExposureTests() => Directory.CreateDirectory(root);
    public void Dispose()
    {
        if (!Path.GetFullPath(root).StartsWith(Path.GetFullPath(Path.GetTempPath()), StringComparison.OrdinalIgnoreCase) || !Path.GetFileName(root).StartsWith("CompositorExposure-")) throw new IOException("Unsafe cleanup.");
        Directory.Delete(root, true);
    }
    private static Document Sample()
    {
        var doc = Document.Create(4, 1);
        var source = doc.Layers[0] with { Pixels = Raster.FromRgba(4, 1, new byte[] { 64, 128, 192, 255, 32, 64, 96, 128, 8, 16, 24, 32, 0, 0, 0, 0 }), Transform = new(0, 0, 4, 1, Sampling: Sampling.Nearest) };
        return doc with { Layers = [source, Layer.ExposureLayer(4, 1) with { Exposure = new(1) }] };
    }
    private static byte[] Pixels(SKImage image)
    {
        using var bitmap = new SKBitmap(CanvasRenderer.Info(image.Width, image.Height));
        Assert.True(image.ReadPixels(bitmap.Info, bitmap.GetPixels(), bitmap.RowBytes, 0, 0)); return bitmap.GetPixelSpan().ToArray();
    }
    private static byte[] Render(Document document, bool white = false)
    { using var renderer = new CanvasRenderer(); using var image = renderer.Flatten(document, white); return Pixels(image); }

    [Theory]
    [InlineData(21, 0, 1)][InlineData(0, .51, 1)][InlineData(0, 0, 0)][InlineData(0, 0, 10)][InlineData(double.NaN, 0, 1)][InlineData(0, double.PositiveInfinity, 1)]
    public void RejectsInvalidSettings(double exposure, double offset, double gamma) =>
        Assert.Throws<InvalidDataException>(() => new ExposureAdjustment(exposure, offset, gamma).Validate());

    [Theory]
    [InlineData(0, 0, 1)][InlineData(1, 0, 1)][InlineData(-2, .05, 1.3)][InlineData(20, -.5, .01)][InlineData(-20, .5, 9.99)]
    public void NativeExposureMatchesLinearLightReferenceAndPreservesEveryAlpha(double stops, double offset, double gamma)
    {
        var settings = new ExposureAdjustment(stops, offset, gamma); var original = new byte[256 * 256 * 4];
        for (int a = 0; a < 256; a++) for (int c = 0; c < 256; c++)
        { int p = (a * 256 + c) * 4; original[p] = original[p + 1] = original[p + 2] = (byte)(a * c / 255); original[p + 3] = (byte)a; }
        var actual = original.ToArray(); NativePixels.Levels(actual, 256 * 256, AdjustmentProcessor.Tables(settings));
        double Curve(int value)
        {
            double s = value / 255.0, linear = s <= .04045 ? s / 12.92 : Math.Pow((s + .055) / 1.055, 2.4);
            linear = Math.Pow(Math.Max(0, linear * Math.Pow(2, stops) + offset), 1 / gamma);
            return Math.Clamp(linear <= .0031308 ? linear * 12.92 : 1.055 * Math.Pow(linear, 1 / 2.4) - .055, 0, 1);
        }
        for (int p = 0; p < actual.Length; p += 4)
        {
            int a = actual[p + 3]; Assert.Equal(original[p + 3], a);
            if (a == 0) { Assert.Equal(0, actual[p]); continue; }
            double x = original[p] * 255.0 / a; int lo = (int)x, hi = Math.Min(255, lo + 1);
            int expected = (int)Math.Round((Curve(lo) + (Curve(hi) - Curve(lo)) * (x - lo)) * a, MidpointRounding.AwayFromZero);
            Assert.InRange((int)actual[p], Math.Max(0, expected - 1), Math.Min(a, expected + 1));
            Assert.Equal(actual[p], actual[p + 1]); Assert.Equal(actual[p], actual[p + 2]);
        }
        if (settings.IsIdentity) Assert.Equal(original, actual);
        var doc = Document.Create(256, 256); doc = doc.Replace(doc.Layers[0] with { Pixels = Raster.FromRgba(256, 256, original) });
        doc = doc with { Layers = doc.Layers.Add(Layer.ExposureLayer(256, 256) with { Exposure = settings }) };
        Assert.True(actual.SequenceEqual(Render(doc)), "Fast composition must match the original C kernel for every alpha and channel byte.");
    }

    [Fact]
    public void AffectsOnlyCompositeBelowAndRemainsLiveWithoutMutatingSource()
    {
        var doc = Sample(); var source = doc.Layers[0].Pixels; var before = source.ToRgba();
        var pixels = Render(doc); Assert.InRange(pixels[0], (byte)89, (byte)91); Assert.InRange(pixels[1], (byte)175, (byte)177);
        for (int p = 3; p < pixels.Length; p += 4) Assert.Equal(before[p], pixels[p]);
        var top = Layer.Blank("Top", 4, 1) with { Pixels = Raster.FromRgba(4, 1, new byte[] { 255, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }) };
        Assert.Equal(new byte[] { 255, 0, 0, 255 }, Render(doc with { Layers = doc.Layers.Add(top) })[..4]);
        var changed = doc.Replace(doc.Layers[0] with { Pixels = ColorAdjustments.Apply(source, new(10)) });
        Assert.NotEqual(pixels, Render(changed)); Assert.Equal(before, source.ToRgba());
        Assert.Equal(before, Render(doc.Replace(doc.Layers[1] with { Visible = false })));
        Assert.Equal(before, Render(doc.Replace(doc.Layers[1] with { Exposure = new() })));
        var empty = Document.Create(4, 1); empty = empty with { Layers = empty.Layers.Add(Layer.ExposureLayer(4, 1) with { Exposure = new(3, .5) }) };
        Assert.All(Render(empty), value => Assert.Equal(0, value)); Assert.All(Render(empty, true), value => Assert.Equal(255, value));
    }

    [Theory]
    [InlineData(BlendMode.Normal)][InlineData(BlendMode.Multiply)][InlineData(BlendMode.Screen)][InlineData(BlendMode.Overlay)]
    [InlineData(BlendMode.Darken)][InlineData(BlendMode.Lighten)][InlineData(BlendMode.Difference)]
    public void BlendOpacitySoftMaskAndGroupsNeverThickenAlpha(BlendMode mode)
    {
        var doc = Sample(); var adjustment = doc.Layers[1]; var group = Layer.Group("Parent", 4, 1) with { Opacity = .5 };
        var grouped = doc with { Layers = [doc.Layers[0], group, adjustment with { ParentId = group.Id, Opacity = .5, Blend = mode, Mask = LayerMask.Solid(1, 1, 128) }] };
        var actual = Render(grouped); var before = Render(doc.Replace(adjustment with { Visible = false }));
        var full = Render(doc.Replace(adjustment with { Blend = mode })); double weight = .25 * 128 / 255.0;
        for (int p = 0; p < actual.Length; p++)
        {
            if (p % 4 == 3) Assert.Equal(before[p], actual[p]);
            else Assert.InRange((int)actual[p], (int)Math.Round(before[p] * (1 - weight) + full[p] * weight) - 1, (int)Math.Round(before[p] * (1 - weight) + full[p] * weight) + 1);
        }
        Assert.Equal(before, Render(grouped.Replace(group with { Visible = false })));
        Assert.Equal(before, Render(grouped.Replace(grouped.Layers[2] with { Mask = LayerMask.Solid(1, 1, 0) })));
        Assert.Equal(Render(doc.Replace(adjustment with { Opacity = .25, Blend = mode })), Render(grouped.Replace(grouped.Layers[2] with { Mask = LayerMask.Solid(1, 1, 0) with { Enabled = false } })));
    }

    [Fact]
    public void MaskTransformsLimitCoverageAndMaskBrushDoesNotCreateSourcePixels()
    {
        var doc = Sample(); var layer = doc.Layers[1] with { Mask = LayerMask.Solid(1, 1), Transform = new(1, 0, 2, 1, Sampling: Sampling.Nearest) };
        var baseline = doc.Layers[0].Pixels.ToRgba(); var full = Render(doc); var clipped = Render(doc.Replace(layer));
        Assert.Equal(baseline[..4], clipped[..4]); Assert.Equal(full[4..12], clipped[4..12]); Assert.Equal(baseline[12..], clipped[12..]);
        Assert.Throws<InvalidOperationException>(() => new BrushStroke(layer, new(20, 1, 1, 255, 0, 0), 4, 1));
        var stroke = new MaskStroke(layer, new(20, 1, 1, 0, 0, 0), 4, 1); stroke.Append(new(2, .5));
        Assert.Empty(layer.Pixels.Tiles); Assert.Equal(baseline, Render(doc.Replace(layer with { Mask = stroke.Mask })));
    }

    [Theory]
    [InlineData(1f)][InlineData(1.5f)][InlineData(2f)]
    public void MultipleAdjustmentsViewportCacheAndUndoMatchCanonicalExport(float scale)
    {
        var doc = Sample(); var second = Layer.ExposureLayer(4, 1) with { Exposure = new(-.7, .02, 1.1), Opacity = .6 };
        doc = doc with { Layers = doc.Layers.Add(second) }; var session = new EditorSession(doc); using var viewport = new ViewportRenderer();
        void Compare()
        {
            using var image = viewport.Render(session.Document, 16, 8, scale, 2, 1);
            using var surface = SKSurface.Create(CanvasRenderer.Info(16, 8)); surface.Canvas.Clear(); surface.Canvas.Translate(2, 1); surface.Canvas.Scale(scale);
            using var renderer = new CanvasRenderer(); using var exported = renderer.Flatten(session.Document);
            surface.Canvas.DrawImage(exported, 0, 0, new SKSamplingOptions(SKFilterMode.Nearest)); using var expected = surface.Snapshot();
            Assert.Equal(Pixels(expected), Pixels(image));
        }
        Compare(); session.Apply(d => d.Replace(second with { Exposure = new(2, 0, .7) })); Compare();
        session.Undo(); Compare(); session.Redo(); Compare();
        session.Apply(d => d.Replace(d.Layers[0] with { Pixels = ColorAdjustments.Apply(d.Layers[0].Pixels, new(20)) })); Compare();
        session.Apply(d => d with { Layers = d.Layers.RemoveAt(1) }); Compare();
    }

    [Fact]
    public void VersionSevenAndEightRoundTripSwiftFieldsMasksAndEditableValues()
    {
        var doc = Sample(); var layer = doc.Layers[1] with { Exposure = new(1.25, -.03, 1.4), Mask = LayerMask.Solid(1, 1, 128) };
        doc = doc.Replace(layer); string path = Path.Combine(root, "Exposure.comp"); ProjectStore.Save(doc, layer.Id, path);
        string manifest = Path.Combine(path, "manifest.json"); var json = JsonNode.Parse(File.ReadAllText(manifest))!;
        var saved = json["layers"]![1]!; Assert.Null(saved["imageFile"]); Assert.NotNull(saved["maskFile"]);
        Assert.Equal("Exposure", (string)saved["adjustment"]!["kind"]!);
        Assert.Equal(4, saved["adjustment"]!["levels"]!["ranges"]!.AsArray().Count); Assert.Equal(4, saved["adjustment"]!["curves"]!["channels"]!.AsArray().Count);
        Assert.Single(Directory.GetFiles(Path.Combine(path, "images"), "*.png").Where(p => !p.EndsWith(".mask.png")));
        json["version"] = 7; File.WriteAllText(manifest, json.ToJsonString()); var loaded = ProjectStore.Load(path);
        Assert.Equal(layer.Exposure, loaded.Document.Layers[1].Exposure); Assert.Equal(Render(doc), Render(loaded.Document));
        var session = new EditorSession(loaded.Document); session.Apply(d => d.Replace(d.Layers[1] with { Exposure = new(2) })); session.Undo();
        Assert.Equal(layer.Exposure, session.ActiveLayer!.Exposure); session.Redo(); Assert.Equal(2, session.ActiveLayer!.Exposure!.Exposure);
        string png = Path.Combine(root, "Exposure.png"); ImageCodec.Export(doc, png, false); Assert.Equal(Render(doc), ImageCodec.Load(png).ToRgba());
        byte[] prior = File.ReadAllBytes(manifest); Assert.Throws<IOException>(() => ProjectStore.SaveInternal(session.Document, layer.Id, path, () => throw new IOException("injected")));
        Assert.Equal(prior, File.ReadAllBytes(manifest));
        saved["adjustment"]!["exposureSettings"] = null; File.WriteAllText(manifest, json.ToJsonString()); Assert.Equal(new(), ProjectStore.Load(path).Document.Layers[1].Exposure);
    }

    [Theory]
    [InlineData("kind")][InlineData("unknown")][InlineData("dormant")][InlineData("version")][InlineData("asset")][InlineData("group")][InlineData("gamma")][InlineData("missing")]
    public void UnsupportedOrInvalidAdjustmentsRefuseOpenAndOverwrite(string failure)
    {
        string path = Path.Combine(root, "Rejected.comp"); var doc = Sample(); ProjectStore.Save(doc, null, path);
        string manifest = Path.Combine(path, "manifest.json"); var json = JsonNode.Parse(File.ReadAllText(manifest))!; var layer = json["layers"]![1]!;
        var adjustment = layer["adjustment"]!;
        switch (failure)
        {
            case "kind": adjustment["kind"] = "Curves"; break;
            case "unknown": adjustment["exposureSettings"]!["future"] = 1; break;
            case "dormant": adjustment["hue"] = 30; break;
            case "version": json["version"] = 6; break;
            case "asset": layer["imageFile"] = "anything.png"; break;
            case "group": layer["isGroup"] = true; break;
            case "gamma": adjustment["exposureSettings"]!["gamma"] = 0; break;
            case "missing": adjustment["exposureSettings"]!.AsObject().Remove("offset"); break;
        }
        File.WriteAllText(manifest, json.ToJsonString()); byte[] prior = File.ReadAllBytes(manifest);
        if (failure is "kind" or "unknown" or "dormant")
        { Assert.Throws<NotSupportedException>(() => ProjectStore.Load(path)); Assert.Throws<NotSupportedException>(() => ProjectStore.Save(doc, null, path)); }
        else
        { Assert.Throws<InvalidDataException>(() => ProjectStore.Load(path)); Assert.Throws<InvalidDataException>(() => ProjectStore.Save(doc, null, path)); }
        Assert.Equal(prior, File.ReadAllBytes(manifest));
    }
}
